### ISSUE TITLE
Meridian Design System MVP Launch Announcement

### ISSUE THREAD

**Issue by garrettdigital** [geocortex/meridian-design#35]
1. Post on Yammer
2. Add link to UI/UX Sharepoint site

**Comment by jfgodin** [comment]
Full post:

### Meridian Design System (beta)

As many of you know the PXD team has quietly been working away on a design system to serve VertiGIS. Prioritizing product work meant the project has been a long time coming, however, you may now rejoice. It is our pleasure to introduce the [Meridian Design System](https://meridian.vertigis.com/)!

The Meridian Design System combines our design principals, design philosophy, and design language into an easy to understand guide. With this design system our goal is to allow VertiGIS to build products that are accessible, recognizable , and allow our customers to easily accomplish their tasks.

The Meridian Design System is a living document and will grow and change over time. If you have any questions or comments please [contact](mailto:grp_ca_pxd@vertigis.com) the PXD team.

**Comment by jfgodin** [comment]
Original post updated!

**Comment by garrettdigital** [comment]
Points 2 & 3 are fixed. But the first point has gotten worse as we've lost all mention of "beta" now.

**Comment by jfgodin** [comment]
> Points 2 & 3 are fixed. But the first point has gotten worse as we've lost all mention of "beta" now.

Updated.

**Comment by garrettdigital** [comment]
Looks good!
